name: Get IP Address
on: [push] # Trigger the workflow on push events

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get IP Address
      run: |
        ip=$(curl -s https://ipinfo.io/ip)
        echo "My IP address is: $ip"
